mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true

find-process-mode: always
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - '+.futu.com'
    - '+.futu.cn'
    - '+.futu.link'
    - '+.futu0.com'
    - '+.futu1.com'
    - '+.futu2.com'
    - '+.futu3.com'
    - '+.futu4.com'
    - '+.futu5.com'
    - '+.futu6.com'
    - '+.futu7.com'
    - '+.futu8.com'
    - '+.futu9.com'
    - '+.futunn.com'
    - '+.futuhn.com'
    - '+.futuhk.com'
    - '+.futusg.com'
    - '+.futufin.com'
    - '+.futustatic.com'
    - '+.futuinc.com'
    - '+.futuniuniu.com'
    - '+.futuesop.com'
    - '+.futuie.com'
    - '+.fututrustee.com'
    - '+.futuholdings.com'
    - '+.moomoo.com'
    - '+.moomoocn.com'
    - '+.moomoo.com.au'
    - '+.moomoo.com.sg'
    - '+.moomoo.com.my'
    - '+.moomoo.com.nz'
    - '+.moomoo.co.jp'

proxy-providers:
  airport-clashmeta:
    type: http
    url: "https://acsub.kyapi.xyz/?sid=283482&uid=134955&token=T2xCNFhvTEYyQUVqMU01T1FCeEVjdEMyNVFSaVBNMVV4TmExYmE2Y0FKND0&app=clashmeta"
    path: ./proxy_providers/airport-clashmeta.yaml
    interval: 86400
    exclude-filter: "^(DIRECT|REJECT|GLOBAL)$"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: PROXY
    type: select
    use:
      - airport-clashmeta
    proxies:
      - DIRECT

rules:
  - PROCESS-NAME,cn.futu.trader,PROXY
  - PROCESS-NAME,cn.futu.trader.universal,PROXY
  - PROCESS-NAME,com.futu.trader,PROXY
  - PROCESS-NAME,com.moomoo.trade,PROXY
  - PROCESS-NAME,com.moomoo.trade.au,PROXY
  - PROCESS-NAME,com.moomoo.trade.ca,PROXY
  - PROCESS-NAME,com.moomoo.trade.jp,PROXY
  - PROCESS-NAME,com.moomoo.trade.my,PROXY
  - PROCESS-NAME,com.moomoo.trade.nz,PROXY
  - DOMAIN-SUFFIX,futu.com,PROXY
  - DOMAIN-SUFFIX,futu.cn,PROXY
  - DOMAIN-SUFFIX,futu.link,PROXY
  - DOMAIN-SUFFIX,futu0.com,PROXY
  - DOMAIN-SUFFIX,futu1.com,PROXY
  - DOMAIN-SUFFIX,futu2.com,PROXY
  - DOMAIN-SUFFIX,futu3.com,PROXY
  - DOMAIN-SUFFIX,futu4.com,PROXY
  - DOMAIN-SUFFIX,futu5.com,PROXY
  - DOMAIN-SUFFIX,futu6.com,PROXY
  - DOMAIN-SUFFIX,futu7.com,PROXY
  - DOMAIN-SUFFIX,futu8.com,PROXY
  - DOMAIN-SUFFIX,futu9.com,PROXY
  - DOMAIN-SUFFIX,futunn.com,PROXY
  - DOMAIN-SUFFIX,futuhn.com,PROXY
  - DOMAIN-SUFFIX,futuhk.com,PROXY
  - DOMAIN-SUFFIX,futusg.com,PROXY
  - DOMAIN-SUFFIX,futufin.com,PROXY
  - DOMAIN-SUFFIX,futustatic.com,PROXY
  - DOMAIN-SUFFIX,futuinc.com,PROXY
  - DOMAIN-SUFFIX,futuniuniu.com,PROXY
  - DOMAIN-SUFFIX,futuesop.com,PROXY
  - DOMAIN-SUFFIX,futuie.com,PROXY
  - DOMAIN-SUFFIX,fututrustee.com,PROXY
  - DOMAIN-SUFFIX,futuholdings.com,PROXY
  - DOMAIN-SUFFIX,moomoo.com,PROXY
  - DOMAIN-SUFFIX,moomoocn.com,PROXY
  - DOMAIN-SUFFIX,moomoo.com.au,PROXY
  - DOMAIN-SUFFIX,moomoo.com.sg,PROXY
  - DOMAIN-SUFFIX,moomoo.com.my,PROXY
  - DOMAIN-SUFFIX,moomoo.com.nz,PROXY
  - DOMAIN-SUFFIX,moomoo.co.jp,PROXY
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - GEOSITE,cn,DIRECT
  - MATCH,PROXY
