mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

proxy-providers:
  airport:
    type: http
    url: "https://acsub.kyapi.xyz/?sid=283482&uid=134955&token=T2xCNFhvTEYyQUVqMU01T1FCeEVjdEMyNVFSaVBNMVV4TmExYmE2Y0FKND0&app=clashmeta"
    path: ./proxy_providers/airport.yaml
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: PROXY
    type: select
    use:
      - airport
    proxies:
      - DIRECT

  - name: FUTU
    type: select
    use:
      - airport
    proxies:
      - PROXY
      - DIRECT

rules:
  - PROCESS-NAME,cn.futu.trader,FUTU
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
